### ISSUE TITLE
Implement Fan speed cycling and toggling

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#19]
From the code:

```
        ###### CYCLE SPEED ######
        # Future enhancement
        #elif action.speedControlAction == indigo.kSpeedControlAction.cycleSpeedControlState:
```

```
        ###### TOGGLE ######
        # Future enhancement
        #elif action.speedControlAction == indigo.kSpeedControlAction.toggle:
```

**Comment by FlyingDiver** [comment]
So does the cycling go through the actual Lutron speeds, or only the speeds known to Indigo?  All of them, I think.

**Comment by rapamatic** [comment]
Yeah, I think the ideal way would be to cycle through all the lutron speeds. Unless you can attach a custom state to the device with the lutron speed, you’ll probably need to query the state of the fan to properly cycle, but that shouldn’t be too hard?

**Comment by FlyingDiver** [comment]
I've added a custom state to represent the actual fan speed, but I use the last reported speed command from the repeater to do the cycling.  That way changes from outside Indigo are handled properly.  At least, I think it'll work.  I don't have a fan controller to test with.

**Comment by rapamatic** [comment]
I'd be happy to test - I've got a few in my house

**Comment by FlyingDiver** [comment]
All changes now available in the latest pre-release.  Read the notes carefully, the changes in the last couple releases are non-reversible in the Indigo database.  Back up first.

**Comment by FlyingDiver** [comment]
Wait, last push was bad.

**Comment by rapamatic** [comment]
No worries... for some reason my SSH/VNC isn't working, so this is going to have to wait until I get home from work anyway (I can't do my normal, reckless, remote beta testing!)

**Comment by FlyingDiver** [comment]
OK, ready when you are.

**Comment by rapamatic** [comment]
I'm getting these errors when I upgrade to 7.2.0 beta 2

```
Started plugin "Lutron RRA2/Caséta 7.2.1"
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - 1st Floor Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - 1st Floor On Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - Away): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - Home): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - Kitchen Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - Kitchen On Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Modes - Suspend): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Scenes - 2nd Floor Lights Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto Scenes - All Lights Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto TT - Front Toggle): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto TT - Inga Bright): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto TT - Inga Off): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto TT - Pio Bright): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Auto TT - Pio Off): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Back Door - All Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Back Door - Garage Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Back Door - Home Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Family Room Bright): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Family Room Off): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Family Room Read): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Family Room Relax): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Kitchen Dim Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Kitchen Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Bright): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Bright LED): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Dim): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Dim LED): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Off): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Off LED): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Read): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(LR - Read LED): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Bath All Off): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Bath Bright): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Bath Dim): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Door Bright): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Door Bright LED): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Door Off): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Door Off LED): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(Master Door Relax): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(To Bed Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(VCRX All Off Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       exception in deviceStartComm(VCRX Home Button): local variable 'roomName' referenced before assignment
   Lutron RRA2/Caséta Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1337, in actionControlSpeedControl
AttributeError: type object 'kSpeedControlAction' has no attribute 'cycleSpeedControlState'

   Lutron RRA2/Caséta Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1337, in actionControlSpeedControl
AttributeError: type object 'kSpeedControlAction' has no attribute 'cycleSpeedControlState'
```

**Comment by FlyingDiver** [comment]
Hmm.  I'll bet you didn't run the device creation process on this database, did you?  I need to account for that in deviceStartComm().

Were you running an action to do the fan speed cycle against a real Fan device?

Please turn on debug logging and run those cycle commands again.

**Comment by FlyingDiver** [comment]
Bah.  The 'roomName' error was just a stupid typo.  roomName != roomname for variable names.

**Comment by rapamatic** [comment]
I'm running this on my live database (I like to live dangerously), so no, I haven't run device creation on this db yet....

I hadn't gotten so far as to try the fan speed action, these errors just occurred on plugin startup...

**Comment by FlyingDiver** [comment]
Huh.  I wonder why it's trying to run that action at startup? I think I need the debug logging, but let me push a version with a fix for the other issue first.

**Comment by FlyingDiver** [comment]
OK, try beta 3.

**Comment by rapamatic** [comment]
Ok, the fixed the variable name typo.... the errors now seem to come up when the code is going through and getting initial states on each device.... I've got two fan controls configured in Indigo, and the errors come up when it is checking the status of other devices in the same area, for example, I have a device "Sebastian - Fan", that seems to be causing this error message:

```
 Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,93,1,
   Lutron RRA2/Caséta Debug       actionControlDimmerRelay sent: "Sebastian - Closet" False ?OUTPUT,93,1,
   Lutron RRA2/Caséta Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1340, in actionControlSpeedControl
AttributeError: type object 'kSpeedControlAction' has no attribute 'cycleSpeedControlState'

   Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,83,1,
   Lutron RRA2/Caséta Debug       actionControlDimmerRelay sent: "Sebastian - Nightstand Lamp" False ?OUTPUT,83,1,
   Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,56,1,
   Lutron RRA2/Caséta Debug       actionControlDimmerRelay sent: "Sebastian - Overhead" False ?OUTPUT,56,1,
```

When I went through and edit/saved on my fans, the actualSpeed custom state was added (this didn't happen automatically).

The custom action worked fine, and after I did the edit/save, the actualSpeed variable would correctly update as I changed the fan state on the fan control.

Even after the edit/save, I still get the error messages above...

**Comment by rapamatic** [comment]
If it helps, I get the same error message when I click the "Send Status Request" button in Indigo....

**Comment by FlyingDiver** [comment]
Do you see "actionControlSpeedControl sent:" in the logs anywhere?

**Comment by rapamatic** [comment]
No, I don't see that in the log. It looks like I'm getting the error message before it even sends the status command to the main repeater. For example, below I have pressed the Send Status Request first for Sebastian - Closet, then for Sebastian - Fan, and then for Sebastian - Closet again - note how it doesn't even seem to send the Fan status request...

```
Apr 5, 2018 at 8:43:33 PM
   Lutron RRA2/Caséta Debug       logLevel = 5
   Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,93,1,
   Lutron RRA2/Caséta Debug       actionControlDimmerRelay sent: "Sebastian - Closet" False ?OUTPUT,93,1,
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,93,1,0.00
   Lutron RRA2/Caséta Debug       Received: Dimmer Sebastian - Closet level set to 0.0
   Lutron RRA2/Caséta Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1340, in actionControlSpeedControl
AttributeError: type object 'kSpeedControlAction' has no attribute 'cycleSpeedControlState'

   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.
   Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,93,1,
   Lutron RRA2/Caséta Debug       actionControlDimmerRelay sent: "Sebastian - Closet" False ?OUTPUT,93,1,
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,93,1,0.00
   Lutron RRA2/Caséta Debug       Received: Dimmer Sebastian - Closet level set to 0.0
   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.

```

**Comment by FlyingDiver** [comment]
I think this is actually an issue with the docs on the speed control device.  What there is of them, which is pretty sketchy.  I think I'm on the trail of a fix.  Will know shortly.

**Comment by FlyingDiver** [comment]
Try Beta 4.  RequestStatus is fixed.  I'm not sure on Toggle.  Cycle is commented out, because I'm starting to think it's not actually implemented in the plugin.

**Comment by rapamatic** [comment]
That seemed to do the trick. Now it's able to check status on the fan:

```
Apr 5, 2018 at 9:05:40 PM
   Lutron RRA2/Caséta Debug       logLevel = 5
   Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,79,1,
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" False ?OUTPUT,79,1,
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,1,0.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 0.0
   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.
```

I have never tried to toggle a fan before, but I just tested it now (via the Toggle Fan On/Off Action)... I was able to toggle the fan On (from an off state), but then I was unable to toggle it Off... got the following debug logs:

```
Apr 5, 2018 at 9:09:03 PM
   Action Group                    test toggle fan
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Toggling on, speed = 100
   Lutron RRA2/Caséta Debug       Sending network command:  #OUTPUT,79,1,100
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" False #OUTPUT,79,1,100
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,1,100.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 100.0
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,29,6
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,30,1,100.00
   Action Group                    test toggle fan
   Lutron RRA2/Caséta Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1351, in actionControlSpeedControl
KeyError: key actualSpeed not found in dict

   Action Group                    test toggle fan
   Lutron RRA2/Caséta Error       Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1351, in actionControlSpeedControl
KeyError: key actualSpeed not found in dict

   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,1,0.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 0.0
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,29,6
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,30,1,0.00

```

**Comment by FlyingDiver** [comment]
Yeah, the toggle code is still pretty iffy.  I'll work on that this weekend.  Kinda busy tomorrow.

Can you try all the other Fan commands, including the new plugin specific actions?  I especially want to know what happens when you execute the cycle command in Device->Fan Speed Controls.  I wrote code for that one, but it's never called.  The docs in the Wiki are really obscure on that one, I think it's actually implemented internally in Indigo.  Which means it'll only use the 4 speeds that Indigo knows about.

**Comment by rapamatic** [comment]
Sure. I’ll play around with those tomorrow. The kids are asleep now, and the fans are in their rooms, so I don’t want to wake them up now.

**Comment by rapamatic** [comment]
Device -> Fan Speed Controls -> Cycle through fan speeds

Fan was off, then went to level 4, 3, 1 and then off - so it is cycling through the Indigo speeds, not the lutron speeds.

Here's the debug log:

```
Apr 7, 2018 at 9:44:33 AM
   Lutron RRA2/Caséta Debug       Sending network command:  ?OUTPUT,79,1,
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" False ?OUTPUT,79,1,
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,1,0.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 0.0
   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.
   Action Group                    test cycle fan
   Lutron RRA2/Caséta Debug       Sebastian - Fan: New speedIndex = 3
   Lutron RRA2/Caséta Debug       Sending network command:  #OUTPUT,79,1,100
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" False #OUTPUT,79,1,100
   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,1,100.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 100.0
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,29,6
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,30,1,100.00
   Action Group                    test cycle fan
   Lutron RRA2/Caséta Debug       Sebastian - Fan: New speedIndex = 2
   Lutron RRA2/Caséta Debug       Sending network command:  #OUTPUT,79,1,75
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" True #OUTPUT,79,1,75
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,1,75.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 75.0
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,29,6
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,30,1,75.00
   Action Group                    test cycle fan
   Lutron RRA2/Caséta Debug       Sebastian - Fan: New speedIndex = 1
   Lutron RRA2/Caséta Debug       Sending network command:  #OUTPUT,79,1,25
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" True #OUTPUT,79,1,25
   Lutron RRA2/Caséta Threaddebug Received an Output message: GNET> ~OUTPUT,79,1,25.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 25.0
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,29,6
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,30,1,25.00
   Action Group                    test cycle fan
   Lutron RRA2/Caséta Debug       Sebastian - Fan: New speedIndex = 0
   Lutron RRA2/Caséta Debug       Sending network command:  #OUTPUT,79,1,0
   Lutron RRA2/Caséta Debug       actionControlSpeedControl sent: "Sebastian - Fan" True #OUTPUT,79,1,0
   Lutron RRA2/Caséta Threaddebug Received an Output message: GNET> ~OUTPUT,79,1,0.00
   Lutron RRA2/Caséta Debug       Sebastian - Fan: Fan speed set to 0.0
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,29,6
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,79,30,1,0.00
   Lutron RRA2/Caséta Threaddebug Command prompt received. Device is ready.
```

**Comment by FlyingDiver** [comment]
I was afraid of that.  I'm currently implementing some speedcontrol commands that were not in the original plugin.  If Indigo uses the (new) increase/decrease commands instead of the direct speed commands then I might be able to do the Lutron increments.  Will have that version this afternoon.

You can switch from detailed debug logging to normal debug logging, if you want.

**Comment by rapamatic** [comment]
Turn Fan Off and Turn Fan On (to last speed) are both not working - nothing shows up in the log when I try those commands.

Increase and Decrease Speed are both not working (I was doing the increase/decrease by "1") - nothing shows up in the low when I try those commands

Set Fan Speed works (to any speed, or to off)

**Comment by FlyingDiver** [comment]
Yeah, none of those were ever actually implemented before.  Almost done now.

**Comment by FlyingDiver** [comment]
So, one last logic problem to figure out.  Right now, it's possible to do a "Turn On" and nothing happens because it's trying to set it to the last commanded speed, which was "0".  That can happen if you do a direct speed command or a decrement speed command.

So, I'm trying to decide if I should only save non-zero speeds as the "last speed" for TurnOn or Toggle commands, or if the last commanded speed was zero to use full speed instead.

**Comment by rapamatic** [comment]
I would think the saving the last non-zero state would be the best... I can’t imagine people decreasing speed step by step from full speed as a way to turn off the fan... so if going from speed 1 -> speed 0 was the last command, then a turn on (and last speed) would go to 1.... but maybe I'm not imaging all the use cases....

**Comment by FlyingDiver** [comment]
I agree.  Beta 5 has all the known commands implemented.  Unfortunately, speed cycling is done using the Indigo speedIndex commands, which only do Indigo speeds.
